const candidates = [
  {
    id: 1,
    name: "John Doe",
    age: 30,
    skills: ["Angular", "React", "Vue"],
    job: "Software Engineer",
    email: "john@gmail.com",
    rating: 3,
    experience: 5,
    picture: "https://randomuser.me/api/portraits/men/42.jpg",
  },
  {
    id: 2,
    name: "Eric Doe",
    age: 25,
    skills: ["Angular", "React", "Vue"],
    job: "Software Engineer",
    email: "eric@gmail.com",
    rating: 1,
    experience: 3,
    picture: "https://randomuser.me/api/portraits/women/59.jpg",
  },
  {
    id: 3,
    name: "John Smith",
    age: 35,
    skills: ["Angular", "React", "Vue"],
    job: "Software Engineer",
    email: "smith@gmail.com",
    rating: 2,
    experience: 7,
    picture: "https://randomuser.me/api/portraits/men/12.jpg",
  },
  {
    id: 4,
    name: "Paul Smith",
    age: 40,
    skills: ["Angular", "React", "Vue"],
    job: "Software Engineer",
    email: "paul@gmail.com",
    rating: 5,
    experience: 10,
    picture: "https://randomuser.me/api/portraits/men/41.jpg",
  },
  {
    id: 5,
    name: "Richard Doe",
    age: 30,
    skills: ["Angular", "React", "Vue"],
    job: "Software Engineer",
    email: "richard@gmail.com",
    rating: 2,
    experience: 5,
    picture: "https://randomuser.me/api/portraits/men/15.jpg",
  },
  {
    id: 6,
    name: "Junior Doe",
    age: 18,
    skills: ["Angular", "React", "Vue"],
    job: "Software Engineer",
    email: "junior@gmail.com",
    rating: 5,
    experience: 1,
    picture: "https://randomuser.me/api/portraits/women/86.jpg",
  },
];

module.exports = { candidates };
